[package]
name = "FinalProject"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[nn]
path = "./FinalProject/src/nn.rs"

[dependencies]
rand = "0.7.3"
rand_distr = "0.2.2"
piston = "0.49.0"
pistoncore-glutin_window = "0.63.0"
piston2d-graphics = "0.36.0"
piston2d-opengl_graphics = "0.72.0"
rayon = "1.3.0"
itertools = "0.9.0"
